Update AMDS Firmware for Timing Manager in AMDC
Severson-Group/AMDS pull request #48
Opened 2024-05-10 18:39 UTC by codecubepi

This PR is a mild revision to the AMDS Firmware that makes its interface compatible with the new Timing Manager IP introduced in  v1.3 of the AMDC Firmware

Add Links
Add More Detail
Need to update docs.amdc.dev page on AMDS Firmware

2024-05-14 01:46 UTC, codecubepi commented
Hey @codecubepi , this PR needs the following before review & close:

- [ ] Test these changes with the old AMDS driver on the AMDC side for sanity sake
- [ ] Test these changes with the new AMDS driver on the AMDC side for real functionality sake
- [ ] When [v1.3](https://github.com/Severson-Group/AMDC-Firmware/pull/372) in AMDC-Firmware is ready for review, this PR is also ready for final review

2024-05-29 17:18 UTC, npetersen2 commented
The default AMDS firmware in this PR works fine, but exhibits a rather large jitter in timing---I believe this issue has been present in the AMDS firmware for years. The end result is that, from the AMDC perspective, the AMDS total sampling time has around `1 us` of jitter. This was observed by @annikaolson during testing of the new `Timing Manager` feature in the AMDC FPGA.

I was doing some testing in the lab to try to figure out why and reduce the jitter. There is no reason the AMDS shouldn't behave EXACTLY the same way for each sampling instance.

I found the issue: the AMDS firmware is totally interrupt-driven: the GPIO EXTI ISR for the `SYNC_ADC` signal from the AMDC triggers the ADC sampling etc. However, there is another ISR lurking, the default `SysTick` ISR. In the current firmware, the SysTick ISR is actually higher priority vs. the SYNC_ADC ISR. Therefore, sometimes, it fires during the sampling which causes the large jitter as the MCU handles the SysTick.

Since the AMDS does not use the SysTick feature, we can simply disable the ISR on boot. Right before the `while(1)` loop in the `main.c` file, add this line of code:

```C
// Disable the SysTick ISR
//
// The SysTick ISR causes jitter in the firmware operation,
// and since this project does not use the SysTick features,
// we do not need it to run during operation!
//
// Set bit 0 to 0
SysTick->CTRL &= 0xFFFFFFFE;
``` 

Based on the scope testing, this reduces the jitter to about 70 ns (about 12 clock cycles), which is simply the MCU ISR handling jitter. Now, the AMDC won't see hardly any jitter when sampling from the AMDS. However, this fix only reduces the jitter---there is still around 10us of latency for the total AMDS sampling and data transmission.

@codecubepi can you add the line of code above to this PR and confirm the AMDS still runs per your local build? Thanks!

2024-08-30 20:19 UTC, npetersen2 requested changes
Thanks @codecubepi.

One comment for us to discuss---I know this code works, has been tested pretty extensively, etc. So, I hesitate to change anything. However, if you read the ADC code, it has some extra complexity with two memory buffers that it ping-pongs between due to the old ISR operation. However, now, since there is only 1 ISR context that does everything, it does not need this complexity. It would be nice to simplify the code a bit, but I am not sure we need to invest the time to do that, test it, etc.... what do you think?

2024-08-30 20:19 UTC, npetersen2 commented on Mainboard/Firmware/motherboard_v1/Core/Src/adc.c
> +	write_buffer_number = 1 - write_buffer_number;
Tab/space issue

2024-08-30 20:24 UTC, codecubepi commented
> Thanks codecubepi.
> 
> One comment for us to discuss---I know this code works, has been tested pretty extensively, etc. So, I hesitate to change anything. However, if you read the ADC code, it has some extra complexity with two memory buffers that it ping-pongs between due to the old ISR operation. However, now, since there is only 1 ISR context that does everything, it does not need this complexity. It would be nice to simplify the code a bit, but I am not sure we need to invest the time to do that, test it, etc.... what do you think?

Well, if I were to fix the code to address the tab/space issue, I might as well just remove the unnecessary buffer code (and do some retesting).

Otherwise it'd be easy to open an issue and have a be a "good first issue" for future contributors... but in all reality it could turn into an issue that never really gets addressed... I think the first option of me just fixing it and retesting is probably the better way to go 🙃

2024-08-31 01:05 UTC, codecubepi commented
@npetersen2 

I took care of removing those obselete double buffers. I ran a hardware test with the fixed [ADC data flushing](https://github.com/Severson-Group/AMDC-Firmware/issues/413), to verify that the AMDS data still matches what is seen by the AMDC's on-board ADC:

![image](https://github.com/user-attachments/assets/0d434e3b-de3a-4c42-9003-5019d3ab3a20)

2024-08-31 16:15 UTC, npetersen2 approved these changes
So nice to have clean code :) Thanks @codecubepi

Best code is no code---115 lines removed!

2024-09-01 00:21 UTC, codecubepi commented
> So nice to have clean code :) Thanks codecubepi
> 
> Best code is no code---115 lines removed!

Haha you're welcome. I can delete more if it'll make you even happier 😂

2024-09-13 02:25 UTC, codecubepi commented
Note from @elsevers : We should start tagging AMDS releases with a version number that matches the AMDC Firmware version number, so user's know when firmware is compatible. So the [previous commit](https://github.com/Severson-Group/AMDS/commit/86abe4d8d466c128ab61d18d4f5d53ca8be6be7e) on `develop` would be tagged `v.1.2.x`, and this merge would get tagged as `v1.3.x`.

2024-09-13 17:49 UTC, npetersen2 commented
Per the release of AMDC-Firmware `v1.3.0`, I believe this PR should be merged, correct @codecubepi ?

2024-09-13 19:13 UTC, codecubepi commented
> Per the release of AMDC-Firmware `v1.3.0`, I believe this PR should be merged, correct codecubepi ?

Yes, let's merge this! See my comment above about version tagging in this repo to match AMDC-Firmware.

2024-09-13 20:10 UTC, merged

2024-09-15 02:19 UTC, elsevers commented
> Note from @elsevers : We should start tagging AMDS releases with a version number that matches the AMDC Firmware version number, so user's know when firmware is compatible. So the [previous commit](https://github.com/Severson-Group/AMDS/commit/86abe4d8d466c128ab61d18d4f5d53ca8be6be7e) on `develop` would be tagged `v.1.2.x`, and this merge would get tagged as `v1.3.x`.

@codecubepi, I compared notes with @npetersen2 on this and we decided on another approach to handle this. From @npetersen2 's message:

> The way you suggested could work, but I worry it will cause too much overhead, and might confuse folks to have X releases that are all exactly the same code... e.g., if the AMDS stays constant, could be easily 10+ releases for "no reason"
The way this is usually done I believe (e.g., in python) is for the AMDS to be released on its own vA.B.C numbering as makes sense, then provide a "requirements" file in the AMDC for each release saying it needs AMDS >= v2 etc.
I could see either way working, but I feel it just adds some overhead to always keep releasing the AMDS when there are no changes, plus I am not sure that codebase will change too much
>
> A future idea would be that the AMDC can query the AMDS at boot-up to determine the firmware version to ensure compatibility :slightly_smiling_face:
>
> Since, for now, this is really strictly a user/human issue, I guess keeping it in the [docs.amdc.dev](http://docs.amdc.dev/) website makes sense, probably on the "https://docs.amdc.dev/getting-started/user-guide/amds-interface/" page near the top, a new section about installing the correct AMDS firmware and a table of compatible versions between the AMDS/AMDC

2024-09-15 04:03 UTC, codecubepi commented
@elsevers @npetersen2 

Yeah, this is a completely fair concern. I'm willing to concede 😄