Add changelog notes for v2.0.0 release
Severson-Group/AMDS pull request #53
Opened 2024-09-16 02:17 UTC by elsevers

Added changelog notes for v2.0.0 release. **Reviewers,** can you please make sure I have captured the release notes correctly?

Related feature PR: 
- #52

## Upon Merging This PR
Per #51, we will
1. Delete release [v1.3.x](https://github.com/Severson-Group/AMDS/releases/tag/v1.3.x)
2. Create a `v2.0.x` branch off of `develop` and set it to be the default repo branch
3. Create a `v2.0.0` release / tag off of the `v2.0.x` branch.

2024-09-17 20:10 UTC, npetersen2 requested changes
I modified the changelog entry to be a bit more accurate.

@codecubepi does this look good to you?

2024-09-17 20:10 UTC, npetersen2 commented on CHANGELOG.md
> +- Remove `SYNC_TX` interrupt
```suggestion
- Sample and transmit data upon receipt of `SYNC_ADC` interrupt
- Remove `SYNC_TX` interrupt
```

2024-09-17 20:29 UTC, codecubepi commented on CHANGELOG.md
> +- Remove `SYNC_TX` interrupt
Yes, I like this change

2024-09-19 02:49 UTC, codecubepi approved these changes
Approved

2024-09-19 03:48 UTC, merged